# Generated by Django 3.2.5 on 2021-07-15 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('instructions', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('image', models.TextField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
    ]
